services:
   redis:
      image: docker.io/valkey/valkey:9-alpine
      #command: valkey-server /etc/valkey.conf


   postgres:
      image: docker.io/postgres:18-alpine
      #environment:
         #- POSTGRES_PASSWORD=asdfasdf # change this
      volumes:
         - postgres-data:/var/lib/postgresql

   flaskbb: &flaskbb
      build:
         context: ./build/
      user: uwsgi:uwsgi
      depends_on:
         - postgres
         - redis
      volumes:
         # FIXME
         - ./config/flaskbb.cfg:/app/flaskbb/flaskbb.cfg
         - ./config/uwsgi.ini:/app/flaskbb/uwsgi.ini
         - ./logs:/app/flaskbb/logs

      image: flaskbb

      command: uwsgi --ini /app/flaskbb/uwsgi.ini

   celery:
      <<: *flaskbb
      command: flaskbb celery worker

volumes:
   postgres-data:
