version: '3'
services:
   redis:
      image: redis:alpine

   postgres:
      image: postgres:9.5-alpine
      environment:
         - POSTGRES_PASSWORD=asdfasdf # change this
      volumes:
         - postgres-data:/var/lib/postgresql

   flaskbb:
      depends_on: 
         - postgres
         - redis
      environment:
         - FLASKBB_SETTINGS=/app/config/flaskbb.cfg
      image: gordonjcp/flaskbb
      volumes:
         - ./themes:/app/themes
         - ./config/flaskbb:/app/config
         - ./logs:/app/logs
      command: gunicorn wsgi:flaskbb -w1 -b0.0.0.0:5000 --access-logfile -

   web:
      depends_on:
         - flaskbb
      volumes:
         - ./web/:/srv/nginx/webroot
         - ./themes:/srv/nginx/themes
         - ./config/nginx:/etc/nginx-flaskbb
      image: nginx:alpine
      command: nginx -c /etc/nginx-flaskbb/nginx.conf

volumes:
   postgres-data:
