version: '3'
services:
   redis:
      image: redis:alpine

   postgres:
      image: postgres:9.5-alpine
      environment:
         - POSTGRES_PASSWORD=asdfasdf
      volumes:
         - postgres-data:/var/lib/postgresql

   flaskbb:
      #build:
      #   context: build/
      #   dockerfile: flaskbb/Dockerfile
      depends_on: 
         - postgres
         - redis
      environment:
         - FLASKBB_SETTINGS=/app/config/flaskbb.cfg
      image: gordonjcp/flaskbb
      volumes:
         #- ./themes:/app/themes
         - ./config:/app/config
         - ./logs:/app/logs
      command: gunicorn wsgi:flaskbb -w1 -b0.0.0.0:5000 --log-file /app/logs/gunicorn.log --log-level debug --access-logfile -

   web:
      #build:
      #   context: build/
      #   dockerfile: nginx/Dockerfile
      depends_on:
         - flaskbb
      image: gordonjcp/flaskbb-nginx
      ports:
         - 80:80
   

volumes:
   postgres-data:
