version: '3'
services:
   redis:
      image: redis:alpine

   postgres:
      image: postgres:9.5-alpine
      environment:
         - POSTGRES_PASSWORD=asdfasdf
      volumes:
         - postgres-data:/var/lib/postgresql

   flaskbb:
      depends_on: 
         - postgres
      environment:
         - FLASKBB_SETTINGS=/app/config/flaskbb.cfg
      image: gordonjcp/flaskbb
      volumes:
         - ./themes:/app/themes
         - ./config:/app/config:ro
         - ./logs:/app/logs
        # - ./config/flaskbb:/app/flaskbb
      #ports:
      #   - 5000:5000
      #command: gunicorn app/config/wsgi:flaskbb -w1 -b0.0.0.0:5000 --log-file /app/logs/gunicorn.log --log-level debug --access-logfile -

   web:
      depends_on:
         - flaskbb
      image: nginx:alpine
      volumes: 
         - ./config/nginx:/etc/nginx-flaskbb:ro
      command: nginx -c /etc/nginx-flaskbb/nginx.conf
      ports:
         - 80:80
   

volumes:
   postgres-data:
