version: '3'
services:
   redis:
      image: redis:alpine

   postgres:
      image: postgres:9.5-alpine
      environment:
         - POSTGRES_PASSWORD=asdfasdf
      volumes:
         - postgres-data:/var/lib/postgresql

   flaskbb:
      depends_on: 
         - postgres
      environment:
         - FLASKBB_SETTINGS=/app/config/flaskbb.cfg
      image: gordonjcp/flaskbb
      volumes:
         - ./themes:/app/themes
         - ./config:/app/config:ro
         - ./logs:/app/logs
      ports:
         - 5000:5000

   web:
      depends_on:
         - flaskbb
      image: nginx:alpine
      volumes: 
         - ./config/nginx:/etc/nginx-flaskbb:ro
      command: nginx -c /etc/nginx-flaskbb/nginx.conf


   

volumes:
   postgres-data: