# command: uwsgi --plugins http,python --http flaskbb:8000 --master -p 1 -w wsgi:flaskbb

[uwsgi]
plugins = http,python
http = flaskbb:8000
master = true
processes=1
module=wsgi:flaskbb
single-interpreter = true
die-on-term = true
static-map=/static=/app/flaskbb/flaskbb/static/
